name: Test
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: test
        run: make test
      - name: coverage
        uses: vladopajic/go-test-coverage@97ecc524075d8ece0e1a406edec1c191e2dd3277
        with:
          profile: cover.out
          local-prefix: github.com/amplify-security/probe
          threshold-file: 80
          threshold-package: 80
          threshold-total: 90
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges